language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t techmefy/multi-react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run techmefy/multi-react-test npm test -- --coverage

after_success:
  - docker build -t techmefy/multi-client ./client
  - docker build -t techmefy/multi-nginx ./nginx
  - docker build -t techmefy/multi-server ./server
  - docker build -t techmefy/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push techmefy/multi-client
  - docker push techmefy/multi-nginx
  - docker push techmefy/multi-server
  - docker push techmefy/multi-worker







